### ISSUE TITLE
Gallery on homepage doesn't appear

### ISSUE THREAD

**Issue by PanchamBro** [niwanetwork/niwa-website#67]
On some devices, the gallery that would normally showcase the wikis doesn't appear, even without using an adblock service. I'm not sure if it on certain devices, but it needs to be fixed.
![image](https://user-images.githubusercontent.com/5955312/124532477-a70c2000-ddde-11eb-8f01-313f1a695369.png)

**Comment by KevinPayravi** [comment]
Resolved, caused by error in members data file.
